CREATE SEQUENCE   "SEQ_BIBL_ABONAMENT";
/
CREATE SEQUENCE   "SEQ_BIBL_AUTOR";
/
CREATE SEQUENCE   "SEQ_BIBL_EGZEMPLARZE";
/
CREATE SEQUENCE   "SEQ_BIBL_KARY";
/
CREATE SEQUENCE   "SEQ_BIBL_KLIENT";
/
CREATE SEQUENCE   "SEQ_BIBL_KSIAZKA";
/
CREATE SEQUENCE   "SEQ_BIBL_WYDAWNICTWO";
/
CREATE SEQUENCE   "SEQ_BIBL_WYPOZYCZENIE";