CREATE TABLE  "BIBL_AUTOR" 
   (	"AUT_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"AUT_IMIE" VARCHAR2(50 CHAR), 
	"AUT_NAZWISKO" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"AUT_DATA_UR" DATE NOT NULL ENABLE, 
	"AUT_DATA_SM" DATE, 
	"AUT_PLEC" VARCHAR2(1 CHAR), 
	 CONSTRAINT "AUT_PLEC_CHECK" CHECK ( aut_plec IN ( 'K', 'M' ) ) ENABLE, 
	 CONSTRAINT "BIBL_AUTOR_PK" PRIMARY KEY ("AUT_ID")
  USING INDEX  ENABLE
   )
/

CREATE TABLE  "BIBL_WYDAWNICTWO" 
   (	"WYD_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"WYD_NAZWA" VARCHAR2(150 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "BIBL_WYDAWNICTWO_PK" PRIMARY KEY ("WYD_ID")
  USING INDEX  ENABLE
   )
/

CREATE TABLE  "BIBL_KSIAZKA" 
   (	"KS_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"KS_TYTUL" VARCHAR2(200 CHAR), 
	"KS_ROK_WYDANIA" NUMBER(4,0), 
	"KS_ISBN" VARCHAR2(13 CHAR), 
	"KS_WYD_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"KS_LICZBA_EGZ" NUMBER(10,0), 
	 CONSTRAINT "BIBL_KSIAZKA_PK" PRIMARY KEY ("KS_ID")
  USING INDEX  ENABLE
   )
/

CREATE TABLE  "BIBL_RODZ_ABNM" 
   ("RAB_KOD" VARCHAR2(3 CHAR) NOT NULL ENABLE, 
	"RAB_NAZWA" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"RAB_CENA" NUMBER(10,2), 
	"RAB_OKRES" NUMBER(10,0), 
	 CONSTRAINT "BIBL_RODZ_ABNM_PK" PRIMARY KEY ("RAB_KOD")
  USING INDEX  ENABLE
   )
/

CREATE TABLE  "BIBL_KLIENT" 
   (	"KL_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"KL_IMIE" VARCHAR2(50 CHAR), 
	"KL_NAZWISKO" VARCHAR2(50 CHAR), 
	"KL_PLEC" VARCHAR2(1 CHAR), 
	"KL_DATA_UR" DATE, 
	 CHECK ( kl_plec IN ( 'K', 'M' ) ) ENABLE, 
	 CONSTRAINT "BIBL_KLIENT_PK" PRIMARY KEY ("KL_ID")
  USING INDEX  ENABLE
   )
/

CREATE TABLE  "BIBL_AUTOR_KSIAZKA" 
   (	"KA_AUT_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"KA_KS_ID" NUMBER(10,0) NOT NULL ENABLE, 
	 CONSTRAINT "BIBL_AUTOR_KSIAZKA_PK" PRIMARY KEY ("KA_AUT_ID", "KA_KS_ID")
  USING INDEX  ENABLE
   )
/
ALTER TABLE  "BIBL_AUTOR_KSIAZKA" ADD CONSTRAINT "BIBL_AUT_BIBL_KS_FK" FOREIGN KEY ("KA_KS_ID")
	  REFERENCES  "BIBL_KSIAZKA" ("KS_ID") ENABLE
/
ALTER TABLE  "BIBL_AUTOR_KSIAZKA" ADD CONSTRAINT "BIBL_KA_BIBL_AUT_FK" FOREIGN KEY ("KA_AUT_ID")
	  REFERENCES  "BIBL_AUTOR" ("AUT_ID") ENABLE
/

CREATE TABLE  "BIBL_EGZEMPLARZE" 
   (	"EGZ_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"EGZ_NUMER" VARCHAR2(30 CHAR), 
	"EGZ_KS_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"EGZ_ROK_DRUKU" NUMBER(4,0), 
	 CONSTRAINT "BIBL_EGZEMPLARZE_PK" PRIMARY KEY ("EGZ_ID")
  USING INDEX  ENABLE
   )
/
ALTER TABLE  "BIBL_EGZEMPLARZE" ADD CONSTRAINT "BIBL_EGZ_BIBL_KS_FK" FOREIGN KEY ("EGZ_KS_ID")
	  REFERENCES  "BIBL_KSIAZKA" ("KS_ID") ENABLE
/

CREATE TABLE  "BIBL_ABONAMENT" 
   (	"ABN_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ABN_DATA_OD" DATE, 
	"ABN_DATA_DO" DATE, 
	"ABN_KL_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ABN_RAB_KOD" VARCHAR2(3 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "BIBL_ABONAMENT_PK" PRIMARY KEY ("ABN_ID")
  USING INDEX  ENABLE
   )
/
ALTER TABLE  "BIBL_ABONAMENT" ADD CONSTRAINT "BIBL_ABN_BIBL_KL_FK" FOREIGN KEY ("ABN_KL_ID")
	  REFERENCES  "BIBL_KLIENT" ("KL_ID") ENABLE
/
ALTER TABLE  "BIBL_ABONAMENT" ADD CONSTRAINT "BIBL_ABN_BIBL_RAB_FK" FOREIGN KEY ("ABN_RAB_KOD")
	  REFERENCES  "BIBL_RODZ_ABNM" ("RAB_KOD") ENABLE
/

CREATE TABLE  "BIBL_WYPOZYCZENIA" 
   (	"WYP_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"WYP_DATA" DATE, 
	"WYP_PLAN_DATA_ZWR" DATE, 
	"WYP_REAL_DATA_ZWR" DATE, 
	"WYP_KL_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"WYP_EGZ_ID" NUMBER(10,0), 
	 CONSTRAINT "BIBL_WYPOZYCZENIA_PK" PRIMARY KEY ("WYP_ID")
  USING INDEX  ENABLE
   )
/
ALTER TABLE  "BIBL_WYPOZYCZENIA" ADD CONSTRAINT "BIBL_WYPOZYCZENIA_EGZ" FOREIGN KEY ("WYP_EGZ_ID")
	  REFERENCES  "BIBL_EGZEMPLARZE" ("EGZ_ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "BIBL_WYPOZYCZENIA" ADD CONSTRAINT "BIBL_WYP_BIBL_KL_FK" FOREIGN KEY ("WYP_KL_ID")
	  REFERENCES  "BIBL_KLIENT" ("KL_ID") ENABLE
/

CREATE TABLE  "BIBL_KARY" 
   (	"KAR_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"KAR_KWOTA" NUMBER(10,2), 
	"KAR_WYP_ID" NUMBER(10,0) NOT NULL ENABLE, 
	 CONSTRAINT "BIBL_KARY_PK" PRIMARY KEY ("KAR_ID")
  USING INDEX  ENABLE
   )
/
ALTER TABLE  "BIBL_KARY" ADD CONSTRAINT "BIBL_KAR_BIBL_WYP_FK" FOREIGN KEY ("KAR_WYP_ID")
	  REFERENCES  "BIBL_WYPOZYCZENIA" ("WYP_ID") ENABLE
/

